### ISSUE TITLE
Implement Redis 4.x missing req/res commands

### ISSUE THREAD

**Issue by sirocchj** [laserdisc-io/laserdisc#19]
Most should be highlighted by `FIXME` and/or `TODO` in code

**Comment by sirocchj** [comment]
Working on this, will open a PR soon

**Comment by sirocchj** [comment]
What's missing (may not be exhaustive):
- [ ] Scripting protocol
- [ ] Tests for PublishP, ServerP, SetP, SortedSetP, StringP and TransactionP
- [ ] Some FIXME and command combinations missing

**Comment by barambani** [comment]
how about separate tickets ?

**Comment by sirocchj** [comment]
Opened #125 #126 and #127
