### ISSUE TITLE
Add laserdisc in the redis.io

### ISSUE THREAD

**Issue by nashid** [laserdisc-io/laserdisc#61]
_Laserdisc_ is not listed here: https://redis.io/clients#

It would a great first step so that we are discoverable by our clients. This would also help to promote this library.

**Comment by sirocchj** [comment]
Just a note: we may want to remove the disclaimer in the README as part of addressing this, now that our production concerns are gone

**Comment by barambani** [comment]
@sirocchj , in relation to that, what do you think about having Mima to check the bincompat in the CI before removing that disclaimer ?

**Comment by sirocchj** [comment]
I absolutely want Mima checking, so yeah great idea!

On the disclaimer removal: I think we'll allow breaking changes until 1.0.0, as most other projects do, we just need to be more principled than we've been so far in doing minor/patch, I guess. I just want to remove any connotation of laserdisc not being production ready that a disclaimer like that could still give to the casual reader.

**Comment by barambani** [comment]
MiMa can wait until we need to keep bincompat then I guess.

**Comment by barambani** [comment]
The last bit here is waiting for https://github.com/antirez/redis-doc/pull/1050 to be closed.

**Comment by barambani** [comment]
It has finally been added, see [here](https://redis.io/clients#scala). Thanks a lot @nashid . I think this can be closed.
